server:
  port: 9100
spring:
  application:
    name: ManufacturersService
  datasource:
    url: jdbc:mysql://localhost:3306/spareparts
    username: root
    password: pass@word1
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true